apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app:  myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-prod
      labels:
        app:  myapp
        type: front-end
    spec:
      containers:
      - name: nginx-controller
        iamge: nginx
  replicas: 3
